#!/bin/bash
######################################################
#### rc.local for OOB Mangement VM - 2025/02/27 - JTW
#### for manual or non standard netplan config - set NO_NETPLAN
######################################################
check_exceptions() {
    for key in "${!exceptions[@]}"; do
      if [ $1 == ${exceptions[$key]} ]
      then
         return 1
      fi
    done
    return 0
}

# Start of Main
# NO_NETPLAN=true
declare -A exceptions
exceptions[FortiAnalyzer]=2
exceptions[FortiManager]=12
exceptions[TCGUI]=90

this_machine=`ip a | awk '
   BEGIN { tap=0 }
   $1 == "link/ether" { tap=1;getline }
   $1 == "inet"       { if (tap==1) {print $2;exit }}
'`
if [ -z "$this_machine" ]
then
    this_machine="172.16.3.80/24"
fi

# get ethernet adapters 1 and 2
ether1=`ip a | awk '
	$1 == "2:" {print $2;exit}
'`
ether2=`ip a | awk '
	$1 == "3:" {print $2;exit}
'`

# other variables
mask=`echo $this_machine | sed 's/^.*\///g'`
this_ip=`echo $this_machine | sed 's/\/.*$//g'`
exceptions[ThisMachine]=`echo $this_ip | awk '{split($0,ip_add,".");printf "%d",ip_add[4]}'`
stub=`echo $this_ip | awk '{split($0,ip_add,".");printf "%d.%d.%d",ip_add[1],ip_add[2],ip_add[3]}'`

# create the .yaml file NOTE - indentation is CRITICAL!
netplan="/etc/netplan/OOB_netplan.yaml"
echo "# DO NOT EDIT THIS FILE!!!" > $netplan
echo "# This is generated from /etc/rc.local and will be rebuilt upon reboot" >> $netplan
echo "network:" >> $netplan
printf "%2sversion: %s\n" "" "2" >> $netplan
printf "%2sethernets:\n" "" >> $netplan
printf "%4s%s\n" "" $ether1 >> $netplan
printf "%6saddresses:\n" "" >> $netplan
printf "%6s- \"%s.%s/%s\"\n" "" $stub ${exceptions[ThisMachine]} $mask >> $netplan

for last_octet in {2..120}
do
	check_exceptions $last_octet && sudo iptables -A PREROUTING -t nat -p tcp -d ${stub}.${last_octet} --dport 1:9000 -j DNAT --to-destination 10.100.55.${last_octet}
    check_exceptions $last_octet && printf "%6s- \"%s.%s/%s\"\n" "" $stub $last_octet $mask >> $netplan
done

# finish up netplan
printf "%6sroutes:\n" "" >> $netplan
printf "%6s- to: %s\n" "" "default" >> $netplan
printf "%8svia: %s\n" "" ${stub}.1 >> $netplan
printf "%6snameservers:\n" "" >> $netplan
printf "%10ssearch: [%s]\n" "" fortinet.internal >> $netplan
printf "%10saddresses: [%s, %s]\n" "" 96.45.45.45 96.45.46.46 >> $netplan
printf "%6saccept-ra: %s\n" "" "false" >> $netplan
printf "%6slink-local: [%s]\n" "" "" >> $netplan
if [ -n "$ether2" ]
then
	printf "%4s%s\n" "" $ether2 >> $netplan
	printf "%6saddresses:\n" "" >> $netplan
	printf "%6s- %s.%s/%s\n" "" 10.100.55 ${exceptions[ThisMachine]} $mask >> $netplan
	printf "%6saccept-ra: %s\n" "" "false" >> $netplan
	printf "%6slink-local: [%s]\n" "" "" >> $netplan
fi
sudo netplan apply
sudo iptables -A POSTROUTING -t nat -o eth1 -j MASQUERADE
